const ESTADOS_COTIZACIONES = {
  INICIAL: "INICIAL",
  GENERADO: "GENERADO",
  RECHAZADO: "RECHAZADO",
  APROBADO: "APROBADO",
  APROBADO_CON_CURSO: "APROBADO_CON_CURSO",
  APROBADO_CON_VENTA: "APROBADO_CON_VENTA",
  CERRADO: "CERRADO",
};

export default ESTADOS_COTIZACIONES; // for
