const ESTADOS_COTIZACIONES = {
  BORRADOR: "BORRADOR",
  ENVIADO: "ENVIADO",
  RECHAZADO: "RECHAZADO",
  APROBADO: "APROBADO",
  GENERADO: "GENERADO",
  GESTIONADO: "GESTIONADO",
};

export default ESTADOS_COTIZACIONES; // for
